#!/bin/bash
head -3 iacta | tail -1                                                                                                                                                                      !i        1,0-1         A
