#!/bin/bash
head -n 3 iacta | tail -n 1                                                                                                                                                                      !i        1,0-1         A
